//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36366
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Meses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Meses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConsoleApplication1.Meses", typeof(Meses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Abril {
            get {
                return ResourceManager.GetString("Abril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string Agosto {
            get {
                return ResourceManager.GetString("Agosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string Dezembro {
            get {
                return ResourceManager.GetString("Dezembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28.
        /// </summary>
        internal static string Fevereiro {
            get {
                return ResourceManager.GetString("Fevereiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string Janeiro {
            get {
                return ResourceManager.GetString("Janeiro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string Julho {
            get {
                return ResourceManager.GetString("Julho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Junho {
            get {
                return ResourceManager.GetString("Junho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string Maio {
            get {
                return ResourceManager.GetString("Maio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string Marco {
            get {
                return ResourceManager.GetString("Marco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Novembro {
            get {
                return ResourceManager.GetString("Novembro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 31.
        /// </summary>
        internal static string Outubro {
            get {
                return ResourceManager.GetString("Outubro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30.
        /// </summary>
        internal static string Setembro {
            get {
                return ResourceManager.GetString("Setembro", resourceCulture);
            }
        }
    }
}
